package com.excilys.librarymanager.exception;

/**
 * <b>DaoException</b>
 * Encapsulator of exceptions generated by the DAO
 * 
 * @author  Javier Martinez <i>[javier-andres.martinez@-boada@ensta.fr]</i>
 * @version 1.0
 * @since   2020-03-19
 */
public class DaoException extends Exception {


    private static final long serialVersionUID = 1L;

    public DaoException() {
		super();
	}

    public DaoException(String message, Throwable cause) {
		super(message, cause);
	}

	public DaoException(String message) {
		super(message);
	}
}