package com.excilys.librarymanager.exception;

/**
 * <b>ServiceException</b>
 * Encapsulator of exceptions generated by the Services
 * 
 * @author  Kevin Sanchez <i>[kevin-alexandro,sanchez-diaz@ensta.fr]</i>
 * @version 1.0
 * @since   2020-03-20
 */
public class ServiceException extends Exception {

    private static final long serialVersionUID = 1L;

    public ServiceException() {
		super();
	}

    public ServiceException(String message, Throwable cause) {
		super(message, cause);
	}

	public ServiceException(String message) {
		super(message);
	}
}